version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - travel-sqldata:/var/opt/mssql

  flight-api:
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionString=${TRAVEL_FLIGHT_DB:-Server=sqldata;Database=Services.FlightDb;User Id=sa;Password=Pass@word}
    - PATH_BASE=${PATH_BASE}
    - SeqServerUrl=${SeqServerUrlVar}
    - LogstashgUrl=${LogstashUrlVar}

   ports:
    - "5101:80"
    - "9101:81"

volumes:
 travel-sqldata:
  external: false
