version: '3.4'

services:
  flight-api:
    image: ${REGISTRY:-travel}/flight.api-${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: src
      dockerfile: Services/Flight/Flight.API/Dockerfile