// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using travel.Services.FlightAPI.Infrastructure;

#nullable disable

namespace Flight.API.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20220904103409_initaldatabase")]
    partial class initaldatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("agency_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("agencyItem_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("flight_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("flightType_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.AgencyAggregate.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "agency_hilo");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AgencyName");

                    b.Property<int>("HandlerId")
                        .HasColumnType("int")
                        .HasColumnName("HandlerId");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.ToTable("Agency", "Agency");
                });

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.AgencyAggregate.AgencyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "agencyItem_hilo");

                    b.Property<int>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("AgencyId");

                    b.Property<int>("HandlerID")
                        .HasColumnType("int")
                        .HasColumnName("handlerItemId");

                    b.Property<int>("HandlerId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedNumber")
                        .HasColumnType("int")
                        .HasColumnName("RequestedNumber");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("HandlerId");

                    b.ToTable("AgencyItems", "Agency");
                });

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.FlightAggregate.FlightItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "flight_hilo");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Destination");

                    b.Property<int>("HandlerId")
                        .HasColumnType("int")
                        .HasColumnName("HandlerId1");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Source");

                    b.Property<decimal>("_discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Discount");

                    b.Property<string>("_flightNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FlightNumber");

                    b.Property<int>("_flightTypeId")
                        .HasColumnType("int")
                        .HasColumnName("HandlerId");

                    b.Property<decimal>("_markup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Markup");

                    b.Property<int>("_minimumquantity")
                        .HasColumnType("int")
                        .HasColumnName("Minimumquantity");

                    b.Property<int>("_remain")
                        .HasColumnType("int")
                        .HasColumnName("Remain");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.ToTable("FlightItem", "Flight");
                });

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.FlightAggregate.Handler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "flightType_hilo");

                    b.Property<string>("_desc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Desc");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Handler", "Flight");
                });

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.AgencyAggregate.Agency", b =>
                {
                    b.HasOne("travel.Services.FlightAPI.Domain.AggregatesModel.FlightAggregate.Handler", null)
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.AgencyAggregate.AgencyItem", b =>
                {
                    b.HasOne("travel.Services.FlightAPI.Domain.AggregatesModel.AgencyAggregate.Agency", null)
                        .WithMany("AgencyItems")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel.Services.FlightAPI.Domain.AggregatesModel.FlightAggregate.Handler", null)
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.FlightAggregate.FlightItem", b =>
                {
                    b.HasOne("travel.Services.FlightAPI.Domain.AggregatesModel.FlightAggregate.Handler", "handler")
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("handler");
                });

            modelBuilder.Entity("travel.Services.FlightAPI.Domain.AggregatesModel.AgencyAggregate.Agency", b =>
                {
                    b.Navigation("AgencyItems");
                });
#pragma warning restore 612, 618
        }
    }
}
